const List<Map> PlacesData = [
    {"name": "Hospital", "image": "assets/images/hospital.jpg"},
    {"name": "Hotel", "image": "assets/images/hotel.jpg"},
    {"name": "Parking Lot", "image": "assets/images/parking_lot.jpg"},
    {"name": "River", "image": "assets/images/river.jpg"},
    {"name": "Bank", "image": "assets/images/bank.jpg"},
    {"name": "Resturant", "image": "assets/images/resturant.jpg"},
    {"name": "Market", "image": "assets/images/market.jpg"},
    {"name": "Police Station", "image": "assets/images/police.jpg"},
    {"name": "Gym", "image": "assets/images/gym.jpg"},
    {"name": "School", "image": "assets/images/school.jpg"},
    {"name": "Bus Stop", "image": "assets/images/bus_stop.jpg"},
    {"name": "Farm", "image": "assets/images/farm.jpg"},
    {"name": "Event Center", "image": "assets/images/event_center.jpg"},
    {"name": "Church", "image": "assets/images/church.jpg"},
    {"name": "Mosque", "image": "assets/images/mosque.jpg"},
    {"name": "Cinema", "image": "assets/images/cinema.jpg"},
    {"name": "Supermarket", "image": "assets/images/supermarket.jpg"},
    {"name": "Park", "image": "assets/images/park.jpg"},
    {"name": "Boutique", "image": "assets/images/boutique.jpg"},
    {"name": "Bakery", "image": "assets/images/bakery.jpg"},
  ];